### ISSUE TITLE
Not compatible with latest version of confluence

### ISSUE THREAD

**Issue by menardorama** [hallowelt/migrate-confluence#88]
Hi
I am trying to migrate a confluence space from the latest non vulnerable version and got issues with the migration space process.

Using the latest stable release there is no content and also no images.

Does anybody got an idea ?

Thanks

**Comment by DvogelHallowelt** [comment]
Hello,
sorry for the delay. We were facing issues as well so we improved the script.
For our test cases we got good results now.

Please pull the latest version and try again.

Kind regards,
Daniel

**Comment by Tedderouni** [comment]
Hi @DvogelHallowelt, which versions of Confluence are covered by your test cases? I'm using Confluence Server 8.5.5 with migrate-confluence 1.2.1 and getting blank pages. I've posted more details in #81 , which mentions that the XML structure has apparently changed (and the OP of that issue was using Confluence 8.3.2).

**Comment by Tedderouni** [comment]
@DvogelHallowelt  While digging into this today, I found that I had installed `pandoc` incorrectly and it wasn't in my $PATH. Once I fixed that and reran the migration and import steps, it worked as designed. So at least in my case, the issue was user error, and I now can confirm that this works successfully with Confluence Server 8.5.5 and migrate-confluence 1.2.1.
